sensitiveCodepaths:
  # Files only allowed authors can modify
  # - 'app.js'
  # - 'controllers/**/*.js'
allowedAuthors:
  usernames:
    # GitHub username
    # - 'john-doe'
    - 'ayomideodukoya'
notificationList:
  # GitHub username or team name
  # - '@DryRunSec/security'
  # - '@john-doe'
  - '@ayomideodukoya'
