sensitiveCodepaths:
  # Files only allowed authors can modify
  # - 'app.js'
  # - 'controllers/**/*.js'
allowedAuthors:
  usernames:
    # GitHub username
    - 'ayomideodukoya'
notificationList:
  # GitHub username or team name
  - '@ayomideodukoya'
